### ISSUE TITLE
Please add an open source license

### ISSUE THREAD

**Issue by remyjette** [mattstevens/xcode-googletest#8]
Hi there! I'd love to use this project to run my googletest tests from within Xcode, but right now I can't because this code isn't released under any sort of license for me to use it. Would you mind adding a `LICENSE` or `LICENSE.md` file to this repo? (see https://help.github.com/articles/adding-a-license-to-a-repository/)

Thanks!

**Comment by mattstevens** [comment]
[GoogleTests.mm](https://github.com/mattstevens/xcode-googletest/blob/master/Bundle/GoogleTests.mm), which contains all of the Google Test integration code does include a license header.

**Comment by remyjette** [comment]
Ah okay thanks!
